name: Publish

on:
  push:
    branches:
      - master

  schedule:
  # * is a special character in YAML so you have to quote this string
  - cron:  '*/30 * * * *'

jobs:
  downtownlawrence:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
          architecture: "x64"

      - name: Upgrade pip
        run: |
          pip install -U pip

      - name: Cache pip
        id: cache-pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install our project requirements
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: |
          python -m pip install -r requirements.txt

      - name: Sync Downtown Lawrence locally
        run: |
          rm -rf _downtown/*
          python sync.py sync-downtownlawrence

      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
